name: football
description: Shows the current ranking of top European football teams. The ranking based on the market values is recalculated daily.
homepage: https://sadra.at
repository: https://github.com/xsadra/european-teams.git
version: 2.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  dartz: ^0.9.2
  data_connection_checker: ^0.3.4
  shared_preferences: ^2.0.5
  dio: ^4.0.0
  flutter_bloc: ^7.0.0
  get_it: ^6.0.0
  sailor: ^0.7.1
  intl_translation: ^0.17.10+1

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/filter.png
